name: bililive_chat_fl
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  badges: ^3.0.2
  bililive_api_fl:
    path: ../bililive_api_fl
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  dio_throttler: ^0.1.0
  event_bus: ^2.0.0
  font_awesome_flutter: ^10.3.0
  logger: ^1.1.0
  provider: ^6.0.5
  queue: ^3.1.0+2
  shared_preferences: ^2.0.17
  sqflite: ^2.2.4+1
  sqflite_common_ffi: ^2.2.1+1
  url_launcher: ^6.1.8

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/noface.gif
